backend:
  name: git-gateway
  branch: main

media_folder: "images/news"
public_folder: "/images/news"

collections:
  - name: "posts"
    label: "News Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD MMMM YYYY", time_format: false }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
